iam_role_name                   = "asa-iam-key-rotation-lambda-assumed-role"
execution_role_name             = "asa-iam-key-rotation-lambda-execution-role"
iam_exception_group             = "IAMKeyRotationExemptionGroup"
primary_account_id              = "<Input vending account number>"
org_list_role                   = "asa-iam-key-rotation-list-accounts-role"
